package helpDesk.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import helpDesk.Controle.AbrirChamadoControle;
import helpDesk.util.Limitador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Leonardo
 */
public class AberturaChamadoView extends javax.swing.JFrame {

    private String nome;
    private String senha;

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    /**
     * Creates new form AberturaChamadoView
     */
    public AberturaChamadoView() {
        initComponents();
        
        jTextFieldCodPatrimônio.setDocument(new Limitador(5, Limitador.TipoEntrada.NUMERO));
        jTextAreaTextChamado.setDocument(new Limitador(250, Limitador.TipoEntrada.TEXTO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        jButtonCriarChamado = new javax.swing.JButton();
        jTextFieldCodPatrimônio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTextChamado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 97, 26));

        jButtonCriarChamado.setBorder(null);
        jButtonCriarChamado.setContentAreaFilled(false);
        jButtonCriarChamado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCriarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarChamadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCriarChamado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 633, 290, 40));

        jTextFieldCodPatrimônio.setBackground(new java.awt.Color(239, 239, 239));
        jTextFieldCodPatrimônio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldCodPatrimônio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodPatrimônio.setBorder(null);
        jTextFieldCodPatrimônio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCodPatrimônio.setDoubleBuffered(true);
        jTextFieldCodPatrimônio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodPatrimônioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodPatrimônio, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 150, 83, 42));

        jScrollPane1.setBackground(new java.awt.Color(239, 239, 239));
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setAlignmentX(2.0F);
        jScrollPane1.setAlignmentY(2.0F);

        jTextAreaTextChamado.setBackground(new java.awt.Color(239, 239, 239));
        jTextAreaTextChamado.setColumns(20);
        jTextAreaTextChamado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaTextChamado.setLineWrap(true);
        jTextAreaTextChamado.setRows(5);
        jTextAreaTextChamado.setAlignmentX(2.0F);
        jTextAreaTextChamado.setAlignmentY(2.0F);
        jTextAreaTextChamado.setBorder(null);
        jTextAreaTextChamado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextAreaTextChamado.setMargin(new java.awt.Insets(8, 8, 8, 8));
        jScrollPane1.setViewportView(jTextAreaTextChamado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 263, 570, 346));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Abertura do Chamado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodPatrimônioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodPatrimônioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodPatrimônioActionPerformed

    private void jButtonCriarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarChamadoActionPerformed
        String codigo = this.getjTextFieldCodPatrimônio().getText();
        if(this.getjTextAreaTextChamado().getText().matches("") && this.getjTextFieldCodPatrimônio().getText().matches("")){
            JOptionPane.showMessageDialog(null, "Descrição do chamado e código de patrimônio não Inserido! Tente novamente");
        }else if(this.getjTextAreaTextChamado().getText().matches("")){
            JOptionPane.showMessageDialog(null, "Descrição do chamado não Inserido! Tente Novamente!");
        }else if(this.getjTextFieldCodPatrimônio().getText().matches("")){
            JOptionPane.showMessageDialog(null, "Código de patrimônio não Inserido! Tente Novamente!");
        }else{
            try {
                JOptionPane.showMessageDialog(null, "Chamado aberto com sucesso.");
                AbrirChamadoControle abrirChamado = new AbrirChamadoControle();
                abrirChamado.novochamado(this);
                MenuFuncionarioView telaDeMenu = new MenuFuncionarioView();
                telaDeMenu.setVisible(true);
                this.setVisible(false);
            } catch (SQLException sql) {
            }
        }
    }//GEN-LAST:event_jButtonCriarChamadoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        MenuFuncionarioView telaDeMenu = new MenuFuncionarioView();
        telaDeMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    public JTextArea getjTextAreaTextChamado() {
        return this.jTextAreaTextChamado;
    }

    public void setjTextAreaTextChamado(JTextArea jTextAreaTextChamado) {
        this.jTextAreaTextChamado = jTextAreaTextChamado;
    }

    public JTextField getjTextFieldCodPatrimônio() {
        return this.jTextFieldCodPatrimônio;
    }

    public void setjTextFieldCodPatrimônio(JTextField jTextFieldCodPatrimônio) {
        this.jTextFieldCodPatrimônio = jTextFieldCodPatrimônio;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void tela(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AberturaChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AberturaChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AberturaChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AberturaChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AberturaChamadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarChamado;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaTextChamado;
    private javax.swing.JTextField jTextFieldCodPatrimônio;
    // End of variables declaration//GEN-END:variables
}
