/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package helpDesk.view;

import javax.swing.JTextField;
import helpDesk.util.Limitador;
import javax.swing.JPasswordField;
import helpDesk.Controle.LoginControle;
import helpDesk.DAO.RealizarLogin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import helpDesk.Principal.PaginaInicial;

/**
 *
 * @author Leonardo
 */
public class LoginFuncionarioView extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginFuncionarioView
     */
    public LoginFuncionarioView() {
        initComponents();
        
        jTextFieldFuncNome.setDocument(new Limitador(50, Limitador.TipoEntrada.TEXTO));
        jPasswordFieldSenha.setDocument(new Limitador(20, Limitador.TipoEntrada.TEXTO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldFuncNome = new javax.swing.JTextField();
        jButtonAcessar = new javax.swing.JButton();
        jButtonAcessarAtendente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordFieldSenha.setBackground(new java.awt.Color(239, 239, 239));
        jPasswordFieldSenha.setBorder(null);
        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 265, 316, 36));

        jTextFieldFuncNome.setBackground(new java.awt.Color(239, 239, 239));
        jTextFieldFuncNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldFuncNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldFuncNome.setBorder(null);
        jTextFieldFuncNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldFuncNome.setDoubleBuffered(true);
        jTextFieldFuncNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFuncNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 316, 36));

        jButtonAcessar.setBorder(null);
        jButtonAcessar.setContentAreaFilled(false);
        jButtonAcessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 290, 40));

        jButtonAcessarAtendente.setBorder(null);
        jButtonAcessarAtendente.setBorderPainted(false);
        jButtonAcessarAtendente.setContentAreaFilled(false);
        jButtonAcessarAtendente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAcessarAtendente.setFocusable(false);
        jButtonAcessarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessarAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 120, 30));

        jLabel1.setBackground(new java.awt.Color(239, 239, 239));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Login Funcionario.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
        if(this.getjTextFieldFuncNome().getText().matches("") && this.getjPasswordFieldSenha().getText().matches("")){
            JOptionPane.showMessageDialog(null, "Usuario e senha não informados");
        }else if(this.getjTextFieldFuncNome().getText().matches("")){
            JOptionPane.showMessageDialog(null, "Usuario não informado");
        }else if(this.getjPasswordFieldSenha().getText().matches("")){
            JOptionPane.showMessageDialog(null, "Senha não informado");
        }else{
            RealizarLogin tela = new RealizarLogin();
            try {
                tela.negar();
            } catch (SQLException ex) {
            }
            try {
                tela.ativar(getjTextFieldFuncNome().getText(), getjPasswordFieldSenha().getText());
            } catch (SQLException ex) {
            }
            try {
                LoginControle login = new LoginControle();
                login.login(this);
            } catch (SQLException sql) {
            }
        }
        
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jTextFieldFuncNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncNomeActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    private void jButtonAcessarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarAtendenteActionPerformed
        LoginAtendenteView tela = new LoginAtendenteView();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAcessarAtendenteActionPerformed

    public JTextField getjTextFieldFuncNome() {
        return this.jTextFieldFuncNome;
    }

    public void setjTextFieldFuncNome(JTextField jTextFieldFuncNome) {
        this.jTextFieldFuncNome = jTextFieldFuncNome;
    }

    public JPasswordField getjPasswordFieldSenha() {
        return jPasswordFieldSenha;
    }

    public void setjPasswordFieldSenha(JPasswordField jPasswordFieldSenha) {
        this.jPasswordFieldSenha = jPasswordFieldSenha;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void tela(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonAcessarAtendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldFuncNome;
    // End of variables declaration//GEN-END:variables
}
