/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package helpDesk.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MenuFuncionarioView extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuFuncionarioView
     */
    public MenuFuncionarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMeusPatrimonios = new javax.swing.JButton();
        jButtonNovoChamado = new javax.swing.JButton();
        jButtonDesconectar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMeusPatrimonios.setBorder(null);
        jButtonMeusPatrimonios.setContentAreaFilled(false);
        jButtonMeusPatrimonios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMeusPatrimonios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeusPatrimoniosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMeusPatrimonios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 226, 510, 44));

        jButtonNovoChamado.setBorder(null);
        jButtonNovoChamado.setContentAreaFilled(false);
        jButtonNovoChamado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoChamadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovoChamado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 345, 510, 44));

        jButtonDesconectar.setBorder(null);
        jButtonDesconectar.setContentAreaFilled(false);
        jButtonDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 582, 252, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Menu Funcionario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMeusPatrimoniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeusPatrimoniosActionPerformed
        try {
            MeusPatrimoniosView telaMeusPatrimonios;
            telaMeusPatrimonios = new MeusPatrimoniosView();
            telaMeusPatrimonios.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMeusPatrimoniosActionPerformed

    private void jButtonNovoChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoChamadoActionPerformed
        AberturaChamadoView tela = new AberturaChamadoView();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNovoChamadoActionPerformed

    private void jButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconectarActionPerformed
        this.setVisible(false);
        LoginFuncionarioView tela = new LoginFuncionarioView();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void tela(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JButton jButtonMeusPatrimonios;
    private javax.swing.JButton jButtonNovoChamado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
